[package]
name = "mailgun_v3"
description = "reqwest based web bindings for Mailgun's v3 JSON API"
readme = "README.md"
repository = "https://github.com/otterandrye/mailgun_v3"
license = "MIT"
version = "0.14.0"
authors = ["Nathan Merritt <nathan@gnmerritt.net>"]
keywords = ["mailgun", "reqwest", "email", "api"]
categories = ["api-bindings"]
edition = "2021"

[dependencies]
chrono = { version = "^0.4.23", default-features = false, features = ["clock"] }
lazy_static = { version = "1.4.0", default-features = false }
regex = { version = "1.7.1", default-features = false }
reqwest = { version = "^0.12", default-features = false, features = ["json", "multipart"] }
serde = { version = "^1.0.152", default-features = false }
serde_derive = { version = "^1.0.152", default-features = false }
serde_json = { version = "^1.0.91", default-features = false }

[dev-dependencies]
mockito = { version = "^0.31", default-features = false }
tokio = { version = "^1.23", default-features = false, features = ["full"] }
